apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
spec:
  releaseName: reflector
  chartRef:
    kind: OCIRepository
    name: reflector
  interval: 12h
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/emberstack/kubernetes-reflector/blob/main/src/helm/values.yaml
  values: {}
