apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: user-apps-source
  namespace: flux-system
spec:
  interval: 1m
  url: http://gogs.gogs.svc.cluster.local:80/flux/user-apps.git
  ref:
    branch: master
  secretRef:
    name: user-apps-source-auth
