apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: happy-server

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: happy-server

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: happy-server
  envs:
  - happy-server.env

resources:
- namespace.yaml
- service.yaml
- deployment.yaml
