# This patch adds an initContainer to the step-certificates Deployment
# to initialize the CA on the PVC before the main container starts.
# This replaces the bootstrap-pvc Job approach.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: step-certificates
  namespace: step-ca
spec:
  template:
    spec:
      # Add initContainer for CA initialization
      initContainers:
        - name: step-ca-init
          image: cr.smallstep.com/smallstep/step-ca:0.29.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "/scripts/step-ca-init.sh"]
          envFrom:
            - configMapRef:
                name: step-ca-init-env
          volumeMounts:
            - name: ca-data
              mountPath: /home/step
            - name: init-script
              mountPath: /scripts
              readOnly: true
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
      volumes:
        - name: init-script
          configMap:
            name: step-ca-init-script
            items:
              - key: step-ca-init.sh
                path: step-ca-init.sh
