apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: happy-server
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - kind: Rule
    match: Host(`happy-server.libre.pod`)
    priority: 1
    services:
    - name: happy-server
      port: 80
