# PostgreSQL component for Happy Server
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: happy-server

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: postgres

configMapGenerator:
- name: happy-postgres-env
  envs:
  - postgres.env

resources:
- pvc.yaml
- deployment.yaml
- service.yaml
