apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: step-issuer
  namespace: step-ca
spec:
  interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: step-certificates
  chartRef:
    kind: HelmRepository
    name: smallstep
  values: {}
