apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frpc

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: frpc

configMapGenerator:
- name: frpc-config
  files:
  - frp.toml
- name: frpc
  envs:
  - frpc.env

resources:
- namespace.yaml
- secret.yaml
- service.yaml
- deployment.yaml
