apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - kind: Rule
    match: Host(`whoami.librepod.dev`)
    priority: 1
    services:
    - name: whoami
      port: 80
