apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: flux-operator
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - kind: Rule
    match: Host(`flux.libre.pod`)
    priority: 1
    services:
    - name: flux-operator
      port: 9080
