apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flux-ingressroute.yaml
  - traefik-tlsstore.yaml

configMapGenerator:
- name: cluster-config-auth
  namespace: flux-system
  options:
    disableNameSuffixHash: true
    annotations:
      reflector.v1.k8s.emberstack.com/reflects: "gogs/cluster-config-auth"
