apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gogs
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - kind: Rule
    match: Host(`git.${BASE_DOMAIN}`)
    priority: 1
    services:
    - name: gogs
      port: 80
