apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: step-certificates
  namespace: step-ca
spec:
  interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chartRef:
    kind: HelmRepository
    name: smallstep
  values:
    kind: Deployment

    bootstrap:
      secrets: false
      enabled: false
      configmaps: false

    inject:
      enabled: false

    existingSecrets:
      enabled: true
      ca: true
      issuer: true
      certsAsSecret: false
      configAsSecret: false
      sshHostCa: false
      sshUserCa: false

    service:
      port: 9000

    ca:
      name: LibrePod
      containerSecurityContext: {}
      db:
        enabled: false
        existingSecrets:
          enabled: true

    persistence:
      enabled: true
      existingClaim: step-certificates-data
      accessModes:
        - ReadWriteOnce
