# This patch adds the root-ca-server sidecar container to the step-certificates pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: step-certificates
  namespace: step-ca
spec:
  template:
    spec:
      containers:
      - name: root-ca-server
        image: nginx:1.29-alpine
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        # Run as UID 1000 (same as step-ca user) to access the PVC
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
        volumeMounts:
        # Mount the PVC to access the root CA certificate
        - name: ca-data
          mountPath: /home/step
          readOnly: true
        # Mount nginx config
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        # Mount landing page directory (not subPath) for proper MIME types
        - name: landing-page
          mountPath: /usr/share/nginx/html
        # Mount emptyDir for writable directories
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-cache
          mountPath: /var/run
        - name: nginx-cache
          mountPath: /tmp
        # Start nginx with proper config
        command: ["sh", "-c"]
        args:
          - |
            # Create temp directories nginx needs
            mkdir -p /tmp/client_temp /tmp/proxy_temp /tmp/fastcgi_temp /tmp/uwsgi_temp /tmp/scgi_temp
            exec nginx -g "daemon off;"
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
      volumes:
      # nginx configuration ConfigMap
      - name: nginx-config
        configMap:
          name: root-ca-nginx-config
      # Landing page ConfigMap
      - name: landing-page
        configMap:
          name: root-ca-landing-page
      # EmptyDir for nginx cache/temp directories
      - name: nginx-cache
        emptyDir: {}
