apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chartRef:
    kind: HelmRepository
    name: traefik
  values:
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
      wireguard:
        port: 51820
        expose:
          default: true
        exposedPort: 51820
        protocol: UDP

    providers:
      kubernetesCRD:
        allowExternalNameServices: true

    priorityClassName: "system-cluster-critical"

    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"

    logs:
      access:
        enabled: true
