---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-config
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-configs
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: OCIRepository
    name: librepod-marketplace
  path: ./infrastructure/cluster-config
  prune: true
  patches: []
  postBuild:
    substitute:
      BASE_DOMAIN: "librepod.dev"
