apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
data:
  config.yaml: |
    model_list:
      - model_name: gpt-4o
        litellm_params:
          model: azure/gpt-4o-ca
          api_base: https://my-endpoint-canada-berri992.openai.azure.com/
          api_key: os.environ/CA_AZURE_OPENAI_API_KEY
    litellm_settings:
      drop_params: true
      success_callback: ["langfuse"]
