apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litellm

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: litellm

configMapGenerator:
- name: litellm
  envs:
  - litellm.env

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- pvc.yaml
- service.yaml
- deployment.yaml
