apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: casdoor

resources:
- ../../base
- ingressroute.yaml

patches:
- path: ./patch-storage-class.yaml
  target:
    kind: PersistentVolumeClaim
# This had to be done, otherwise the casdoor were deployed to the default namespace
- target:
    kind: Deployment|Service|ServiceAccount|ConfigMap|Pod|IngressRoute
  patch: |
    - op: add
      path: /metadata/namespace
      value: casdoor
