apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-easy-config
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: nfs-client
