apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: litellm

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: litellm

configMapGenerator:
- name: postgres-config
  envs:
  - postgres.env

resources:
- deployment.yaml
- service.yaml
- pvc.yaml
