---
apiVersion: source.extensions.fluxcd.io/v1beta1
kind: ArtifactGenerator
metadata:
  name: flux-system-artifact-generator
  namespace: flux-system
spec:
  sources:
    - kind: GitRepository
      name: flux-system
      alias: monorepo
  artifacts:
    - name: infrastructure
      originRevision: "@monorepo"
      copy:
        - from: "@monorepo/infrastructure/**"
          to: "@artifact/"
    - name: librepod-system
      originRevision: "@monorepo"
      copy:
        - from: "@monorepo/apps/casdoor/**"
          to: "@artifact/librepod-system/casdoor/"
        # Add more system apps here as needed:
        # - from: "@monorepo/apps/traefik"
        #   to: "@artifact/librepod-system/traefik/"
    # - name: apps
    #   originRevision: "@monorepo"
    #   copy:
    #     - from: "@monorepo/apps/**"
    #       to: "@artifact/apps/"
