apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - casdoor.yaml
  - cert-manager.yaml
  - flux-operator-mcp.yaml
  - gogs.yaml
  - nfs-provisioner.yaml
  - oauth2-proxy.yaml
  - step-certificates.yaml
  - step-issuer.yaml
  - traefik.yaml
  - wg-easy.yaml
  - whoami.yaml
