apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: open-webui
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: librepod-apps
  path: ./apps/open-webui/overlays/librepod
  prune: true
  wait: true
  postBuild:
    substitute:
      BASE_DOMAIN: "${BASE_DOMAIN}"
