apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: step-issuer
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: librepod-apps
  path: ./apps/traefik/overlays/librepod
  prune: true
  wait: true
